name: Markdown Lint

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  readme-lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Markdown Linting Action
      uses: avto-dev/markdown-lint@v1.5.0
      with:
        args: './README.md'