name: Markdown Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  readme-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Markdown Linting Action
        uses: DavidAnson/markdownlint-cli2-action@v23
        with:
          globs: "README.md"
